colors:
    # Default colors
    primary: ##1D1F21
        background: "#1D1F21" # base
        foreground: "#C6E0E0" # text
        # Bright and dim foreground colors
        dim_foreground: "#C6E0E0" # text
        bright_foreground: "#C6E0E0" # text

    # Cursor colors
    cursor:
        text: "#1D1F21" # base
        cursor: "#F2D5CF" # rosewater
    vi_mode_cursor:
        text: "#1D1F21" # base
        cursor: "#BABBF1" # lavender

    # Search colors
    search:
        matches:
            foreground: "#1D1F21" # base
            background: "#A5ADCE" # subtext0
        focused_match:
            foreground: "#1D1F21" # base
            background: "#A6D189" # green
        footer_bar:
            foreground: "#1D1F21" # base
            background: "#A5ADCE" # subtext0

    # Keyboard regex hints
    hints:
        start:
            foreground: "#1D1F21" # base
            background: "#E5C890" # yellow
        end:
            foreground: "#1D1F21" # base
            background: "#A5ADCE" # subtext0

    # Selection colors
    selection:
        text: "#1D1F21" # base
        background: "#F2D5CF" # rosewater

    # Normal colors
    normal:
        black: "#45475A" # surface1
        red: "#F38BA8" # red
        green: "#A6E3A1" # green
        yellow: "#F9E2AF" # yellow
        blue: "#89B4FA" # blue
        magenta: "#F5C2E7" # pink
        cyan: "#3FDCEB" # teal
        white: "#BAC2DE" # subtext1

    # Bright colors
    bright:
        black: "#585B70" # surface2
        red: "#F38BA8" # red
        green: "#A6E3A1" # green
        yellow: "#F9E2AF" # yellow
        blue: "#89B4FA" # blue
        magenta: "#F5C2E7" # pink
        cyan: "#3FDCEB" # teal
        white: "#A6ADC8" # subtext0

    # Dim colors
    dim:
        black: "#45475A" # surface1
        red: "#F38BA8" # red
        green: "#A6E3A1" # green
        yellow: "#F9E2AF" # yellow
        blue: "#89B4FA" # blue
        magenta: "#F5C2E7" # pink
        cyan: "#3FDCEB" # teal
        white: "#BAC2DE" # subtext1

    indexed_colors:
        - { index: 16, color: "#FE640B" }
        - { index: 17, color: "#DC8A78" }
